services:
  browser:
    image: lscr.io/linuxserver/chromium:latest  # lscr.io/linuxserver/chromium:latest  lscr.io/linuxserver/librewolf:latest
    container_name: librewolf
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - LIBREWOLF_CLI=https://www.linuxserver.io/ #optional
      - LC_ALL=zh_CN.UTF-8 # utf-8编码
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=font-noto-cjk # 语言包#中日韩
      - CUSTOM_USER=admin
      - PASSWORD=admin@1314.
    # volumes:
    #   - ./config:/config
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped