services:
  webtop:
    image: lscr.io/linuxserver/webtop:latest
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
      - LC_ALL=zh_CN.UTF-8 # utf-8编码
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=font-noto-cjk # 语言包#中日韩
      - CUSTOM_USER=admin
      - PASSWORD=admin@1314.
    volumes:
      # - ./admin/config:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 8000:3000
      - 8001:3001

    shm_size: "1gb" #optional
    restart: unless-stopped