services:
  nezha:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nezha-dashboard
    # image: 395784985/argo-nezha:v1
    restart: always
    ports:
      - "8008:8008"
    volumes:
      - ./nezha_data:/dashboard/data
    environment:
      - TZ=Asia/Shanghai
      - ARGO_DOMAIN=${ARGO_DOMAIN:-}
      - CF_TOKEN=${CF_TOKEN:-}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID:-}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME:-}
      - R2_ENDPOINT_URL=${R2_ENDPOINT_URL:-}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY:-}
    networks:
      - nezha-network

networks:
  nezha-network:
    driver: bridge
