---
services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    security_opt:
      - apparmor:rootlesskit #optional
    environment:
      - KASM_PORT=443
      - DOCKER_HUB_USERNAME=admin #optional
      - DOCKER_HUB_PASSWORD=admin@1314. #optional
      - DOCKER_MTU=1500 #optional
    volumes:
      - ./kasm/data:/opt
      - ./kasm/profiles:/profiles #optional
      - /dev/input:/dev/input #optional
      - /run/udev/data:/run/udev/data #optional
    ports:
      - 3000:3000
      - 443:443
    restart: unless-stopped